# -*- coding: utf-8 -*-
"""Menghitung luas object citra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1skerNGSAdd5lzPGGYyS2HzgQE_1ucTFz
"""

!pip install opencv-python
import cv2
import numpy as np
from matplotlib import pyplot as plt

from google.colab import files
uploaded = files.upload()

image_path = list(uploaded.keys())[0]
image = cv2.imread(image_path)
original_image = image.copy()

print("1. Original Image")

plt.imshow(cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB))
plt.title('Original Image')
plt.show()

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
print("2. Convert to Grayscale")

plt.imshow(gray, cmap='gray')
plt.title('Grayscale Image')
plt.show()

blurred = cv2.GaussianBlur(gray, (5, 5), 0)
print("3. Apply Gaussian Blur")

plt.imshow(blurred, cmap='gray')
plt.title('Blurred Image')
plt.show()

edges = cv2.Canny(blurred, 50, 150)
print("4. Apply Canny Edge Detection")

plt.imshow(edges, cmap='gray')
plt.title('Canny Edges')
plt.show()

dilated = cv2.dilate(edges, None, iterations=2)
print("5. Apply Dilation")

plt.imshow(dilated, cmap='gray')
plt.title('Dilated Image')
plt.show()

contours, _ = cv2.findContours(dilated, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

min_contour_area = 200
print("6. Find Contours")

vertical_offset = 20

pixels_to_cm2 = 0.01

# menghitung luas kontur dalam pixel
for contour in contours:
    # menghitung luas dalam pixel dan mengkonversi ke sentimeter menggunakan faktor konversu pixels_to_cm2
    area_pixels = cv2.contourArea(contour)
    area_cm2 = area_pixels * pixels_to_cm2

    #  memeriksa jika luas contur memenuhi batas minimum yg disimpan divariabel min_contour_area
    if area_pixels > min_contour_area:
        # menghitung titkpusat dari kontur
        M = cv2.moments(contour)
        if M["m00"] != 0:
            cx = int(M["m10"] / M["m00"])
            cy = int(M["m01"] / M["m00"])

            #  menggambar kontur dari gambar asli dengan line hijau
            cv2.drawContours(image, [contour], -1, (0, 255, 0), 2)

            # menabahkan tekse ke gambar dengan informasi luas dalam sentimeter
            font = cv2.FONT_HERSHEY_SIMPLEX
            cv2.putText(image, f"{area_cm2:.2f} cm²", (cx - 50, cy - 10), font, 0.3, (0, 0, 0), 1)

            # menambahkan label "cm²"
            cv2.putText(image, "cm²", (cx - 50, cy + vertical_offset), font, 0.3, (255, 255, 255), 1)

print("7. Final Result")

plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB))
plt.title('Original Image')

plt.subplot(1, 2, 2)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.title('Contours with Area Labels')

plt.show()

